[package]
name = "sudoku"
version = "0.1.0"
authors = ["Steven Malis <smmalis37@gmail.com>"]
edition = "2018"

[dependencies]
druid = { git = "https://github.com/smmalis37/druid", rev = "7f89fdc7e6c3fa9d279fa9c01b2da7735364fefc" }
radix_fmt = "1.0"
arraytools = "0.1.5"

[profile.release]
lto = true
