[package]
name = "sudoku"
version = "0.1.0"
authors = ["Steven Malis <smmalis37@gmail.com>"]
edition = "2018"

[dependencies]
druid = "0.7"
radix_fmt = "1.0"
arraytools = "0.1.5"
arrayvec = "0.5"

[profile.release]
lto = true
