[package]
name = "sudoku"
version = "0.1.0"
authors = ["Steven Malis <smmalis37@gmail.com>"]
edition = "2018"

[dependencies]
druid = { git = "https://github.com/smmalis37/druid", rev = "5fa855b" }
radix_fmt = "1.0"
arraytools = "0.1.5"

[profile.release]
lto = true
