[package]
name = "sudoku"
version = "0.1.0"
authors = ["Steven Malis <smmalis37@gmail.com>"]
edition = "2018"

[dependencies]
druid = { git = "https://github.com/linebender/druid", rev = "fb43cf3409f4b2285263913a60cadb73c828f934" }
radix_fmt = "1.0"

[profile.release]
lto = true